### ISSUE TITLE
Can't enter ISO date like 2015-02-06

### ISSUE THREAD

**Issue by spillej** [rhiokim/haroopad#465] opened 2015-02-06 15:38 UTC
Whenever I start writing the date 2015-02-06

it automatically change the line to

**Comment by spillej** [comment] 2015-02-06 15:41
I mean

 without comment ;-)

**Comment by a1880** [comment] 2015-02-07 11:01
This is probably caused by the error reported as issue https://github.com/rhiokim/haroopad/issues/447

**Comment by rhiokim** [comment] 2015-02-25 02:42
@spillej Yep it's the bug. @a1880 thanks.
It'll be fixed with upcoming version.

**Closed as completed by rhiokim** 2015-02-25 02:42 UTC
Labels: bug
