### ISSUE TITLE
Typing key "6" makes line start with "######" (Win 7, 64-bit) 

### ISSUE THREAD

**Issue by rly** [rhiokim/haroopad#459] opened 2015-01-25 01:39 UTC
Every time I press the 6 on my keyboard, six #s are added to the start of the line that I am on. This is quite annoying. I tried pressing all other numbers, letters, and basic US symbols available on the keyboard and pressing only the 6 does something unexpected.

If the line already has 6 #s at the start, then pressing 6 makes the 6 #s go away. So pressing 6 basically toggles whether the line is a Header Level 6 or not.

If I try to type 6 in the middle of the line, the above toggling of the 6 #s at the start of the line occurs, and also a 6 is added to the end of the line instead of in the middle of the line.

Typing 6 on the keyboard numpad does not trigger the above behavior.

**Comment by oshihirii** [comment] 2015-01-27 08:53
I am also experiencing this issue.  

I also seem to get four plus symbols, ie  `++++`, when pressing `Ctrl` + `y` (with the intention of 'redoing' an action).

**Comment by pid1** [comment] 2015-02-03 14:55
This is a duplicate of https://github.com/rhiokim/haroopad/issues/447, which will be fixed in the next release.

**Comment by sprintr** [comment] 2015-02-24 20:44
I am still facing it in 0.13.0.

**Comment by pid1** [comment] 2015-02-24 21:08
@sprintr It is fixed in milestone 0.13.1, which has not been released yet. Please see https://github.com/rhiokim/haroopad/issues/447.

**Comment by pid1** [comment] 2015-02-24 21:09
@rhiokim This bug should be marked as closed.

**Comment by sprintr** [comment] 2015-02-24 21:13
@pid1 Any ETA on 0.13.1

**Comment by rhiokim** [comment] 2015-02-25 02:24
Sorry late. v0.13.1 release soon. Please wait more.

**Closed as completed by rhiokim** 2015-02-25 02:24 UTC
Labels: bug
